# Generated by Django 4.2.3 on 2023-07-05 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuildwarHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atk_user_name', models.CharField(max_length=50)),
                ('atk_hero1', models.CharField(max_length=30)),
                ('atk_hero2', models.CharField(max_length=30)),
                ('atk_hero3', models.CharField(max_length=30)),
                ('atk_hero1_death', models.BooleanField()),
                ('atk_hero2_death', models.BooleanField()),
                ('atk_hero3_death', models.BooleanField()),
                ('atk_hero1_etc', models.TextField()),
                ('atk_hero2_etc', models.TextField()),
                ('atk_hero3_etc', models.TextField()),
                ('def_user_name', models.CharField(max_length=30)),
                ('def_hero1', models.CharField(max_length=30)),
                ('def_hero2', models.CharField(max_length=30)),
                ('def_hero3', models.CharField(max_length=30)),
                ('def_hero1_death', models.BooleanField()),
                ('def_hero2_death', models.BooleanField()),
                ('def_hero3_death', models.BooleanField()),
                ('def_hero1_etc', models.TextField()),
                ('def_hero2_etc', models.TextField()),
                ('def_hero3_etc', models.TextField()),
                ('is_atk_victory', models.BooleanField()),
                ('is_def_victory', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('atk_guild_name', models.CharField(max_length=30)),
                ('atk_guild_rank', models.IntegerField()),
                ('def_guild_name', models.CharField(max_length=30)),
                ('def_guild_rank', models.IntegerField()),
                ('season_name', models.CharField(max_length=30)),
                ('is_public', models.BooleanField()),
            ],
        ),
    ]
